### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by shiftingtech**
apparently we need to turn off some more stuff in menuconfig now

### CODE REVIEW

**Comment by timmit99** [comment]
Okay, good to know. Have you validated this change? If so I'll take your judgment as an approval @shiftingtech

**Comment by shiftingtech** [comment]
@timmit99  still seeing people getting burned by this.

**Comment by timmit99** [comment]
@shiftingtech any chance you could duplicate this file into the klipper expander repository? That needs to be updated as well and then I can merge this.

**Comment by shiftingtech** [comment]
@timmit99  Done

**Review by timmit99 — APPROVED** [review]
All looks good!

**Pull request merged**
