### PR TITLE
New hall effect sensor

### PR DESCRIPTION
**Pull request by christophmuellerorg**
I replaced the previous Honeywell Sensor which has its sensitivity across its Z axis with a Coto RR112-1G42-53, a Hall sensor with its  its sensitivity oriented along the X axis. This change should revert the behavior back to the old through hole design while still allowing for cheaper SMD assembly.

honeywell_vs_coto

Note: please don't merge yet, I first would like to order the PCBs and verify the functionality.

### CODE REVIEW

**Comment by raymondh2** [comment]
Part of why said part was chosen is it is available on JLCPCB assembly service.

**Comment by christophmuellerorg** [comment]
> Part of why said part was chosen is it is available on JLCPCB assembly service.
Thats all nice and I see the appeal of being able to order the boards all assembled from one manufacturer, however it is no excuse for using a part which is not suited well for the purpose. The orthogonal sensor alignment results in a much much lower magnetic field seen by the sensor, low enough that it is causing regular issues due to people having nearby ferromagnetic material as part of the board mounting hardware. 

That goes as far that I have seen cases where people actually get an **inverted** behavior of the sensor triggering all the time except for when close to the magnet and the only explanation for that I have is that some parts of their mounting hardware or the carriage are slightly magnetic with the field being bend when getting close to the magnet. 

Truth be told, most people get their boards parts preassembled from Aliexpress or from distributors like Fermio rather than ordering the board from JLCPCB and I think we should make sure that these boards are as good as they can be. In the moment we are in a situation where I have to recommend people to buy the board from Blurolls in all places because they still use the old through hole design. I don't want to have to recommend Blurolls :-/

**Comment by raymondh2** [comment]
@timmit99 @thebrakshow

**Comment by VinnyCordeiro** [comment]
If a newer component is better suited for the application but the usual fab house does not use it, nor allow the client to buy it for assembly, it's time to change the fab house.

JLCPCB isn't the only company in China to provide PCB assembly. It is possibly the cheaper, but that also limits PCB designers to their component library. Companies like PCBway, Smart Prototyping, Elecrow, and others, allows you to specify a component for assembly without the limitation of so-called libraries. The price may be higher, but the benefit outweighs that. Also, ordering in higher quantities allows for better unit prices.

**Comment by kris4net** [comment]
https://pl.aliexpress.com/item/1005001419239135.html  ???

**Pull request closed without merging**
