### PR TITLE
LDO V0 Display instructions

### PR DESCRIPTION
**Pull request by JaY-III**
LDO Specific instructions

### CODE REVIEW

**Comment by timmit99** [comment]
What's different here vs the standard instructions?

**Comment by JaY-III** [comment]
> What's different here vs the standard instructions?

Just trying to make it super simple for the LDO display.  It's just a Step by step, do this with minimal thinking, plus examples of what you are expecting to see over SSH.  And have everything in a single location.   Right now you need to follow your guide them goto the software section to get the rest of the instructions.

If you don't find it helpful, that's cool. The LDO kits are coming so just trying to help where I can.

**Comment by timmit99** [comment]
In my opinion, I think it would be better suited to just merge the two instructions then. One instruction set.

**Comment by timmit99** [comment]
I'm gone for the next week but when I get back I'd love to discuss this more

**Comment by JaY-III** [comment]
> I'm gone for the next week but when I get back I'd love to discuss this more

One instruction set.
That is a very valid statement. 

Safe travels.

**Pull request closed without merging**
