### PR TITLE
Add Hartk LGX PCB adapter step and heatset version

### PR DESCRIPTION
**Pull request by th3fallen**
Add step file for OG PCB mount adapter and heatset version i guess I never committed the step in his original repo.

### CODE REVIEW

**Comment by timmit99** [comment]
@hartk1213  how does this look?

**Comment by hartk1213** [comment]
> 

Looks good to me👍🏻

**Comment by hartk1213** [comment]
@th3fallen just change the orientation for printing👍🏻

**Comment by raymondh2** [comment]
@th3fallen The orrientation needs updated

**Pull request closed without merging**
